### ISSUE TITLE
Update travis to utilize CMake and install new dependencies

### ISSUE THREAD

**Issue by rdittrich97** [y2s82/goblin_camp#32]
Since we merged goblincamp_ng there are new dependencies  such as Boost, SDL2 and libtcod.  The build system was also changed from boost.build to cmake. All of these changes need to be reflected in the .travis.yml file.

**Comment by y2s82** [comment]
Travis still has few quirks.  This issue is being reopened.

**Comment by rdittrich97** [comment]
#38 Fixed this. Closing this issue
