### ISSUE TITLE
Fixes to .travis.yml

### ISSUE THREAD

**Issue by humphd** [y2s82/goblin_camp#48]
A few things I see in your `.travis.yml` file:

* https://github.com/y2s82/goblin_camp/blob/master/.travis.yml#L17 should be `scons` vs. `scon`
* watch your tab vs. spaces https://github.com/y2s82/goblin_camp/blob/master/.travis.yml#L5

cc @rdittrich97

**Comment by y2s82** [comment]
is .yml file similar to python in terms of how it interpret the white space?
